services:
  - type: web
    name: dreamevents
    runtime: node
    buildCommand: npm run install:all && npm run build --prefix client
    startCommand: npm run start --prefix server
    envVars:
      - key: PORT
        value: 5000
      - key: MONGO_URI
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false

